### ISSUE TITLE
Library Name Change

### ISSUE THREAD

**Issue by HoraceGonzalez** [vivainio/Fapper#3] opened 2018-02-05 18:49 UTC
Love the idea! This is definitely something community needs. The name, though is unfortunate because despite best intentions, it may not pass the HR "sniff test", which will undoubtedly hurt adoption.

Looking forward to giving this a test drive!

**Comment by HoraceGonzalez** [comment] 2018-02-05 18:52
What about FASTSql (F# AST for SQL)?

**Comment by vivainio** [comment] 2018-02-05 19:21
There is already https://www.nuget.org/packages/FastSql/

**Comment by vivainio** [comment] 2018-02-05 20:28
Duplicate of #1

**Closed as completed by vivainio** 2018-02-05 20:28 UTC
